-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 13:14:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventarioASR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventarioASR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventarioASR` DEFAULT CHARACTER SET utf8 ;
USE `inventarioASR` ;

-- -----------------------------------------------------
-- Table `inventarioASR`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`roles` (
  `idrol` INT NOT NULL,
  `role_type` NVARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`usuarios` (
  `idusuario` INT NOT NULL,
  `nombre` NVARCHAR(50) NOT NULL,
  `apellidoP` NVARCHAR(50) NOT NULL,
  `apellidoM` NVARCHAR(50) NOT NULL,
  `claveIdentificacion` NVARCHAR(20) NOT NULL COMMENT 'Este atributo es para hacer referencia a la clave de docente para el caso de los docentes o la matricula para el caso de los alumnos. Este atributo servira como user_name para el acceso a la plataforma.',
  `contraASR` NVARCHAR(100) NOT NULL,
  `fdn` DATE NULL,
  `idrol` INT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `idrol_idx` (`idrol` ASC),
  CONSTRAINT `idrol`
    FOREIGN KEY (`idrol`)
    REFERENCES `inventarioASR`.`roles` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`areas` (
  `idarea` INT NOT NULL,
  `area` NVARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`ubicaciones` (
  `idubicacion` INT NOT NULL,
  `edificio` NVARCHAR(45) NOT NULL,
  `salon` NVARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`productos` (
  `idproducto` INT NOT NULL,
  `inventory_num` BIGINT NOT NULL,
  `serial_num` BIGINT NOT NULL,
  `color` NVARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `date_modified` DATE NULL,
  `brand` NVARCHAR(45) NULL,
  `model` NVARCHAR(45) NULL,
  `idarea` INT NULL,
  `idubicacion` INT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `idarea_idx` (`idarea` ASC),
  INDEX `idubicacion_idx` (`idubicacion` ASC),
  CONSTRAINT `idarea`
    FOREIGN KEY (`idarea`)
    REFERENCES `inventarioASR`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idubicacion`
    FOREIGN KEY (`idubicacion`)
    REFERENCES `inventarioASR`.`ubicaciones` (`idubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`responsables` (
  `idresponsable` INT NOT NULL,
  `docente_id` INT NULL,
  `nombre` NVARCHAR(50) NOT NULL,
  `apellidoP` NVARCHAR(50) NOT NULL,
  `apellidoM` NVARCHAR(50) NOT NULL,
  `claveDocente` VARCHAR(20) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idresponsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`tipoEstados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`tipoEstados` (
  `idtipoEstado` INT NOT NULL,
  `tipo` NVARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idtipoEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`estadosDeProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`estadosDeProductos` (
  `idestadosDeProductos` INT NOT NULL,
  `idproducto` INT NULL,
  `idtipoEstado` INT NULL,
  `comentario` VARCHAR(45) NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idestadosDeProductos`),
  INDEX `idproducto_idx` (`idproducto` ASC),
  INDEX `idtipoEstado_idx` (`idtipoEstado` ASC),
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `inventarioASR`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipoEstado`
    FOREIGN KEY (`idtipoEstado`)
    REFERENCES `inventarioASR`.`tipoEstados` (`idtipoEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`responsableDeProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`responsableDeProducto` (
  `idresponsableDeProducto` INT NOT NULL,
  `idresponsable` INT NULL,
  `idproducto` INT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idresponsableDeProducto`),
  INDEX `idresponsable_idx` (`idresponsable` ASC),
  INDEX `idproducto_idx` (`idproducto` ASC),
  CONSTRAINT `idresponsable`
    FOREIGN KEY (`idresponsable`)
    REFERENCES `inventarioASR`.`responsables` (`idresponsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `inventarioASR`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarioASR`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarioASR`.`sesiones` (
  `idsesion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `token` NVARCHAR(150) NOT NULL,
  `tiempoIni` TIMESTAMP NOT NULL,
  `tiempoFin` TIMESTAMP NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idsesion`),
  INDEX `idusuario_idx` (`idusuario` ASC),
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `inventarioASR`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
