-- MySQL Script generated by MySQL Workbench
-- Sat Mar 28 22:10:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idrol` INT NOT NULL,
  `role_type` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuario` INT NOT NULL,
  `nombre` NVARCHAR(50) NOT NULL,
  `apellidoP` NVARCHAR(50) NOT NULL,
  `apellidoM` NVARCHAR(50) NOT NULL,
  `claveIdentificacion` NVARCHAR(20) NOT NULL COMMENT 'Este atributo es para hacer referencia a la clave de docente para el caso de los docentes o la matricula para el caso de los alumnos. Este atributo servira como user_name para el acceso a la plataforma.',
  `contraASR` NVARCHAR(100) NOT NULL,
  `fdn` DATE NULL,
  `idrol` INT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `idrol_idx` (`idrol` ASC) VISIBLE,
  CONSTRAINT `idrol`
    FOREIGN KEY (`idrol`)
    REFERENCES `mydb`.`roles` (`idrol`)
    ON DELETE CASCADE--Se debe poner not null cuando se elimine y en la actualizacion si debe ser en cascade
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areas` (
  `idarea` INT NOT NULL,
  `area` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ubicaciones` (
  `idubicacion` INT NOT NULL,
  `edificio` NVARCHAR(45) NOT NULL,
  `salon` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idproducto` INT NOT NULL,
  `inventory_num` BIGINT NOT NULL,
  `serial_num` BIGINT NOT NULL,
  `color` NVARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `date_modified` DATE NULL,
  `brand` NVARCHAR(45) NULL,
  `model` NVARCHAR(45) NULL,
  `idarea` INT NULL,
  `idubicacion` INT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `idarea_idx` (`idarea` ASC) VISIBLE,
  INDEX `idubicacion_idx` (`idubicacion` ASC) VISIBLE,
  CONSTRAINT `idarea`
    FOREIGN KEY (`idarea`)
    REFERENCES `mydb`.`areas` (`idarea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idubicacion`
    FOREIGN KEY (`idubicacion`)
    REFERENCES `mydb`.`ubicaciones` (`idubicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsables` (
  `idresponsable` INT NOT NULL,
  `docente_id` INT NULL,
  `nombre` NVARCHAR(50) NOT NULL,
  `apellidoP` NVARCHAR(50) NOT NULL,
  `apellidoM` NVARCHAR(50) NOT NULL,
  `claveDocente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idresponsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoEstados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoEstados` (
  `idtipoEstado` INT NOT NULL,
  `tipo` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadosDeProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estadosDeProductos` (
  `idestadosDeProductos` INT NOT NULL,
  `idproducto` INT NULL,
  `idtipoEstado` INT NULL,
  `comentario` VARCHAR(45) NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idestadosDeProductos`),
  INDEX `idproducto_idx` (`idproducto` ASC) VISIBLE,
  INDEX `idtipoEstado_idx` (`idtipoEstado` ASC) VISIBLE,
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `mydb`.`productos` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idtipoEstado`
    FOREIGN KEY (`idtipoEstado`)
    REFERENCES `mydb`.`tipoEstados` (`idtipoEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsableDeProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsableDeProducto` (
  `idresponsableDeProducto` INT NOT NULL,
  `idresponsable` INT NULL,
  `idproducto` INT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  PRIMARY KEY (`idresponsableDeProducto`),
  INDEX `idresponsable_idx` (`idresponsable` ASC) VISIBLE,
  INDEX `idproducto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `idresponsable`
    FOREIGN KEY (`idresponsable`)
    REFERENCES `mydb`.`responsables` (`idresponsable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `mydb`.`productos` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
